spring:
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://localhost:27071/payment}
  kafka:
    cancelordertopic: "cancelorder"
    ordercreatedtopic: "orderevent"
    expireordertopic: "expireorder"
    paymentTopic: "paymentStatusTopic"
    paymentconsumers:
      group-id: payment-service-listeners
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties[request.timeout.ms]: 600000
    admin:
      properties:
        bootstrap-servers: kafka-service:9092
    bootstrap-servers: kafka-service:9092

server:
  port: 8084
  error:
    include-message: always

STRIPE_SECURE_KEY: ${STRIPE_KEY:8Xc5HXT4fRYeGL5uLyNgaGg4vtMldmLhjtIvD2gLoK4=}
